<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-11
 * Time: 09:11
 */

namespace app\common\model;


use think\Model;

class AdvIndex extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;

}