<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.6.2
 * Time: 16:05
 */

namespace app\common\model;


use think\Log;
use think\Model;

class OrderDet extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 保存订单详情
     * @param $orderInfo
     * @return array
     * @throws \Exception
     */
    public function saveOrderDet($orderInfo)
    {
        $good_list = $orderInfo['good_list'];
        $shop_id = $orderInfo['shop_id'];
        $data = [];
        foreach ($good_list as $good) {
            $temp['order_no'] = $orderInfo['order_no'];
            $temp['shop_id'] = $shop_id;
            $temp['user_id'] = USER_ID;
            $temp['good_id'] = $good['good_id'];
            $temp['good_prop'] = $good['prop_id'];
            $temp['sale_price'] = $good['sale_price'];
            $temp['cost'] = $good['active_price'];
            $temp['num'] = $good['num'];
            $temp['good_name'] = $good['good_name'];
            $temp['prop_name'] = $good['prop_name'];
            $temp['good_image'] = $good['good_image'];
            $temp['gno'] = $good['gno'];
            $data[] = $temp;
        }
        $res = $this->saveAll($data);
        if ($res) {
            return ['code' => 1];
        } else {
            return ['code' => -1];
        }
    }

    public function getDetail($order_no)
    {
        $list =  $this->alias('a')->field('a.cost, a.num, a.cost*a.num total_money, a.good_name, a.prop_name, b.img image')->join('goods b', 'a.good_id=b.id')->where('order_no', $order_no)->select();
        $data = [];
        foreach ($list as $l){
            $temp = $l;
            $temp['image'] = explode(",", $l['image'])[0];
            $data[] = $temp;
        }
        return $data;
    }

    /**
     * 库存修改
     */
    public function decGoods($order_no)
    {
        if(!$order_no){
            return false;
        }else{
            $list = $this->where('order_no', $order_no)->select();
            try{
                foreach ($list as $val){
                    if($val['good_prop']>0){
                        \model('goods_prop')->where(['id', $val['good_prop']])->setDec('num', $val['num']);
                    }else{
                        \model('goods')->where('id', $val['good_id'])->setDec('count', $val['num']);
                    }
                }
            }catch (\Exception $e){
                Log::error('库存减少异常'.$e->getMessage());
            }
        }
    }


}