<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/19
 * Time: 15:34
 */

namespace app\shop\controller;


use think\Controller;

class ShopBase extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(request()->controller() != 'Index'){
            $this->assign('breadNav', $this->getBreadNav());
        }
        if(!self::checkIsLogin()){
            $this->redirect('Pub/login');
        }
    }

    /**
     * 检验商户的合法性
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkIsLogin()
    {
        if (session(config('shopkey'))) {
            if (!defined('SHOP_ID')) {
                define('SHOP_ID', session(config('shopkey')));
            }
            return true;
        } else {
            if(cookie('shop_id') && cookie('shop_pwd')){
                $shop = model('shop')->where([
                    'id'=>cookie('shop_id'),
                    'password'=>cookie('shop_pwd')
                ])->find();
                if($shop){
                    session(config('shopkey'), $shop['id']);
                    if (!defined('SHOP_ID')) {
                        define('SHOP_ID', session(config('shopkey')));
                    }
                    return true;
                }
            }
            return false;
        }
    }

    /**
     * 获取面包屑导航
     */
    private function getBreadNav()
    {
        require_once APP_PATH . 'shop/leftmenu.php';
        $menuArr = $leftmenu;
        $action = request()->controller();
        $method = request()->action();
        $bread = "";
        foreach ($menuArr as $m) {
            foreach ($m['navChild'] as $t){
                if($t['url'] == $action.'/'.$method){
                    $bread = '<i class="Hui-iconfont">&#xe67f;</i> ' . $m['navName'] . ' <span class="c-gray en">&gt;</span> ' . $t["navName"] ;
                    break;
                }
            }
        }
        return $bread;
    }



}