<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/23
 * Time: 13:44
 */

namespace app\app\controller;


use think\Controller;
use think\Log;

class BaseUser extends Controller
{
    /**
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!self::checkUser(input('userid'))) {
            exit_json(-1, '用户不存在');
        }
        Log::error($_POST);
    }

    /**
     * 检验用户是否存在/已登录
     * @param $userid
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkUser($userid)
    {
        if (!$userid) {
            return false;
        }
        $userModel = new \app\common\model\User();
        $res = $userModel->where('id', 'eq', $userid)->find();
        if ($res) {
            if (!defined('USER_ID')) {
                define('USER_ID', $userid);
            }
            if (!defined('CARD_ID')) {
                define('CARD_ID', $res['card_id']);
            }
            model('user')->save(['logintime'=>date('Y-m-d H:i:s')], ['id'=>$userid]);
            return true;
        } else {
            return false;
        }
    }

    /**
     * 检验店铺合法性
     */
    public function checkShop($shop_id)
    {
        if($shop_id){
            $shopModel = new \app\common\model\Shop();
            $shop = $shopModel->where('id', 'eq', $shop_id)->find();
            if($shop){
                return true;
            }else{
                return '店铺信息不存在';
            }
        }else{
            return '店铺信息不存在';
        }

    }

}